default_config={
    '400':'Bad Request',
    '401':'Unauthorized',
    '402':'Payment Required',
    '403':'Forbidden',
    '404':'Not Found',
    '405':'Method Not Allowed',
    '406':'Not Acceptable',
    '407':'Proxy Authentication Required',
    '408':'Request Timeout',
    '409':'Conflict',
    '410':'Gone',
    '411':'Length Required',
    '412':'Precondition Failed',
    '413':'Request Entity Too Large',
    '414':'Request URI Too Long',
    '415':'Unsupported Media Type',
    '416':'Requested Range Not Satisfiable',
    '417':'Expection Failed',
    '418':'I\'m A Teapot',
    '420':'Enhance Your Calm',
    '422':'Unprocessable Entity',
    '423':'Locked',
    '426':'Upgrade Required',
    '444':'No Response',
    '451':'Unavailable for Legal Reasons',
    '500':'Internal Server Error',
    '501':'Not Implemented',
    '502':'Bad Gateway',
    '503':'Service Unavailable',
    '504':'Gateway timeout',
    '505':'HTTP Version Not Supported',
    '506':'Variant Also Negotiates',
    '507':'Insufficient Storage',
    '508':'Loop Detected',
    '509':'Bandwidth Limit Exceeded',
    '510':'Not Extended',
    '511':'Network Authentication Required',
}
